// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5lqpx3LcARcSuhA5MTu89-l0MsMNlYpc',
    appId: '1:600295442046:web:aa7a1d2cec66e9cf5cba2f',
    messagingSenderId: '600295442046',
    projectId: 'test-delta-90b5c',
    authDomain: 'test-delta-90b5c.firebaseapp.com',
    storageBucket: 'test-delta-90b5c.appspot.com',
    measurementId: 'G-GBFZ8ZFHXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNJBrhnyb2S3S9IAbx8qv1JXkCVQH0sLA',
    appId: '1:600295442046:android:cde03b99c598bfdc5cba2f',
    messagingSenderId: '600295442046',
    projectId: 'test-delta-90b5c',
    storageBucket: 'test-delta-90b5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmd6WtWEQQbs3ryddb0mnIqzZ8aVtv18',
    appId: '1:600295442046:ios:7c9a0b8bc6286f3d5cba2f',
    messagingSenderId: '600295442046',
    projectId: 'test-delta-90b5c',
    storageBucket: 'test-delta-90b5c.appspot.com',
    iosClientId: '600295442046-nja69k6q0dsj633avl26rvrnqv058dae.apps.googleusercontent.com',
    iosBundleId: 'com.example.testDelta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcmd6WtWEQQbs3ryddb0mnIqzZ8aVtv18',
    appId: '1:600295442046:ios:7c9a0b8bc6286f3d5cba2f',
    messagingSenderId: '600295442046',
    projectId: 'test-delta-90b5c',
    storageBucket: 'test-delta-90b5c.appspot.com',
    iosClientId: '600295442046-nja69k6q0dsj633avl26rvrnqv058dae.apps.googleusercontent.com',
    iosBundleId: 'com.example.testDelta',
  );
}
